# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: yarn && yarn fetch-algorithms
    command: yarn dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

github:
  prebuilds:
    addBadge: true
    addComment: false
    addCheck: false
    master: true
    branches: true
    pullRequestsFromForks: true

vscode:
  extensions:
    - davidanson.vscode-markdownlint
