name: Bug report
description: Create a report about a technical issue on the website.
title: "[BUG] <description>"
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description of the bug
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Add screenshots of the bug (optional)
    validations:
      required: false
  - type: input
    id: context
    attributes:
      label: Add any other context about the problem here
    validations:
      required: false
