name: Content issue
description: Create a report about a content issue on the website (for example two entries
  for the same algorithm).
title: "[CONTENT] <description>"
labels: [content]
body:
  - type: input
    id: description
    attributes:
      label: Description of the content report
      description: Provide a detailed description of the content error you found
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Add screenshots of the content report (if applicable)
      description: Add any screenshots where we can see the error
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional information/context
      description: Is there anything else we should know about this content report?
    validations:
      required: false
