name: Feature request
description: Suggest an idea for this project.
title: "[FEATURE] <description>"
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Description of the feature request
      description: Provide a detailed description of the change or addition you are proposing
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Add screenshots of the feature request (if applicable)
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional information/context
      description: Is there anything else we should know about this feature?
    validations:
      required: false
