const aliases = {
  algorithms: {
    ordenamientoburbuja: "Bubble Sort",
    ordenamientoradix: "Radix Sort",
    ordenamientodemntonheapsort: "Heap Sort",
    ordenamientodeinsercin: "Insertion Sort",
    ordenamientoshell: "Shell Sort",
    ordenamientodefusin: "Merge Sort",
    ordenamientodeseleccin: "Selection Sort",
    ordenamientorpido: "Quick Sort",
    bsquedabinaria: "Binary Search",
    bsquedalineal: "Linear Search",
    bsquedaexponencial: "Exponential Search",
    exponentialsearch: "Exponential Search",
    cifradocesar: "Caesar Cipher",
    bellmanford: "Bellman Ford",
    doblelistavinculada: "Doubly Linked List",
    listasingularvinculada: "Singly Linked List",
    promedio: "Average Mean",
    numerosfibonacci: "Fibonacci",
    detectordeharris: "Harris Detector",
    cambiodemonedas: "Coin Change",
    coinchange: "Coin Change",
    subsecuenciacomnmslarga: "Longest Common Subsequence",
    fibonacci: "Fibonacci Numbers",
    fibonaccinumber: "Fibonacci Numbers",
    degreetoradian: "Degrees to Radians",
    radians: "Degrees to Radians",
    radiantodegree: "Radians to Degrees",
    fermatlittletheorem: "Fermats Little Theorem",
    nthuglynumber: "Ugly Numbers",
    hashsdbm: "SDBM",
    sdbm: "SDBM",
    avl: "AVL Tree",
    avltree: "AVL Tree",
    aliquotsumcalculator: "Aliquot Sum",
    arithmetic: "Arithmetic Mean",
    arithmeticmean: "Arithmetic Mean",
    stackusinglinkedlist: "Stack with Singly Linked List",
    stackoflinkedlist: "Stack with Singly Linked List",
    stackusinglinkedlists: "Stack with Singly Linked List",
    stacklinkedlist: "Stack with Singly Linked List",
    stacklinkedlistwithlist: "Stack Linked List with List",
    stackusingsinglylinkedlist: "Stack with Singly Linked List",
    linkedliststack: "Stack with Singly Linked List",
    linkedstack: "Stack with Singly Linked List",
    armstrongnumbers: "Armstrong Number",
    armstrong: "Armstrong Number",
    isarmstrong: "Armstrong Number",
    xor: "XOR Cipher",
    xorcipher: "XOR Cipher",
    sudoku: "Sudoku Solver",
    sudokusolver: "Sudoku Solver",
    perfectsquare: "Perfect Square",
    perfectsquarechecker: "Perfect Square",
    lcm: "LCM",
    findlcm: "LCM",
    lcmsum: "LCM",
    lcmofnnumbers: "LCM",
    ispronic: "Pronic Number",
    pronicnumber: "Pronic Number",
    primenumber: "Prime",
    primenumbers: "Prime",
    prime: "Prime",
    checkprime: "Prime",
    primecheck: "Prime",
    anagram: "Anagram",
    anagrams: "Anagram",
    checkanagram: "Check Anagram",
    checkanagrams: "Check Anagram",
    detectanagrams: "Check Anagram",
    anagramchecker: "Check Anagram",
    eulerstotient: "Euler's Totient",
    eulerstotientfunction: "Euler's Totient",
    eulertotient: "Euler's Totient",
    a000010eulerstotient: "Euler's Totient",
    perfectnumber: "Perfect Number",
    perfectnumbers: "Perfect Number",
    perfectnumberchecker: "Perfect Number",
  },
  categories: {
    sorting: "Sorts",
    sorters: "Sorts",
    sort: "Sorts",
    sortingalgorithms: "Sorts",
    searching: "Searches",
    search: "Searches",
    other: "Others",
    misc: "Others",
    maths: "Math",
    hash: "Hashing",
    hashes: "Hashing",
    graph: "Graphs",
    divideconquer: "Divide And Conquer",
    string: "Strings",
    binarytrees: "Binary Tree",
    arrays: "Array",
    linkedlists: "Linked List",
    lists: "List",
    mathematics: "Math",
    trees: "Tree",
    arithmeticanalysis: "Numerical Analysis",
    bom: "Backward Oracle Matching",
    sbom: "Set Backward Oracle Matching",
    cipher: "Ciphers",
    conversion: "Conversions",
    queue: "Queues",
    stack: "Stacks",
    disjointsets: "Disjoint Set",
    caches: "Cache",
    knapsackproblem: "Knapsack",
  },
};
export default aliases;
