module.exports = {
  bubblesort: ["Ordenamiento Burbuja"],
  radixsort: ["Ordenamiento Radix"],
  heapsort: ["Ordenamiento de mónton (heap sort)"],
  insertionsort: ["Ordenamiento de inserción"],
  shellsort: ["Ordenamiento Shell"],
  mergesort: ["Ordenamiento de fusión"],
  selectionsort: ["Ordenamiento de selección"],
  quicksort: ["Ordenamiento rápido"],
  binarysearch: ["Búsqueda binaria"],
  linearsearch: ["Búsqueda lineal"],
  caesarcipher: ["Cifrado Cesar"],
  bellmanford: ["Bellman Ford"],
  doublylinkedlist: ["Doble lista vinculada"],
  singlylinkedlist: ["Lista singular vinculada"],
  averagemean: ["Promedio"],
  fibonaccinumbers: ["Numeros_Fibonacci"],
  harrisdetector: ["Detector de Harris"],
  coinchange: ["Cambio de monedas"],
  longestcommonsubsequence: ["Subsecuencia común más larga"],
};
