module.exports = {
  algorithms: {
    ordenamientoburbuja: "bubblesort",
    ordenamientoradix: "radixsort",
    ordenamientodemntonheapsort: "heapsort",
    ordenamientodeinsercin: "insertionsort",
    ordenamientoshell: "shellsort",
    ordenamientodefusin: "mergesort",
    ordenamientodeseleccin: "selectionsort",
    ordenamientorpido: "quicksort",
    bsquedabinaria: "binarysearch",
    bsquedalineal: "linearsearch",
    bsquedaexponencial: "exponentialsearch",
    cifradocesar: "caesarcipher",
    bellmanford: "bellmanford",
    doblelistavinculada: "doublylinkedlist",
    listasingularvinculada: "singlylinkedlist",
    promedio: "averagemean",
    numerosfibonacci: "fibonaccinumbers",
    detectordeharris: "harrisdetector",
    cambiodemonedas: "coinchange",
    subsecuenciacomnmslarga: "longestcommonsubsequence",
  },
  categories: {
    sorting: "Sorts",
    sorters: "Sorts",
    sort: "Sorts",
    searching: "Searches",
    search: "Searches",
    other: "Others",
    misc: "Others",
    maths: "Math",
    hash: "Hashing",
    hashes: "Hashing",
    graph: "Graphs",
    divideconquer: "Divide And Conquer",
    string: "Strings",
  },
};
