const aliases = {
  algorithms: {
    ordenamientoburbuja: "Bubble Sort",
    ordenamientoradix: "Radix Sort",
    ordenamientodemntonheapsort: "Heap Sort",
    ordenamientodeinsercin: "Insertion Sort",
    ordenamientoshell: "Shell Sort",
    ordenamientodefusin: "Merge Sort",
    ordenamientodeseleccin: "Selection Sort",
    ordenamientorpido: "Quick Sort",
    bsquedabinaria: "Binary Search",
    bsquedalineal: "Linear Search",
    bsquedaexponencial: "Exponential Search",
    exponentialsearch: "Exponential Search",
    cifradocesar: "Caesar Cipher",
    bellmanford: "Bellman Ford",
    doblelistavinculada: "Doubly Linked List",
    listasingularvinculada: "Singly Linked List",
    promedio: "Average Mean",
    numerosfibonacci: "Fibonacci",
    detectordeharris: "Harris Detector",
    cambiodemonedas: "Coin Change",
    coinchange: "Coin Change",
    subsecuenciacomnmslarga: "Longest Common Subsequence",
    fibonacci: "Fibonacci Numbers",
    fibonaccinumber: "Fibonacci Numbers",
  },
  categories: {
    sorting: "Sorts",
    sorters: "Sorts",
    sort: "Sorts",
    searching: "Searches",
    search: "Searches",
    other: "Others",
    misc: "Others",
    maths: "Math",
    hash: "Hashing",
    hashes: "Hashing",
    graph: "Graphs",
    divideconquer: "Divide And Conquer",
    string: "Strings",
    binarytrees: "Binary Tree",
    arrays: "Array",
    linkedlists: "Linked List",
    lists: "List",
    mathematics: "Math",
    trees: "Tree",
    arithmeticanalysis: "Numerical Analysis",
    bom: "Backward Oracle Matching",
    sbom: "Set Backward Oracle Matching",
    cipher: "Ciphers",
  },
};
export default aliases;
