module.exports = {
  algorithms: {
    bubblesort: ["Ordenamiento Burbuja"],
    radixsort: ["Ordenamiento Radix"],
    heapsort: ["Ordenamiento de mónton (heap sort)"],
    insertionsort: ["Ordenamiento de inserción"],
    shellsort: ["Ordenamiento Shell"],
    mergesort: ["Ordenamiento de fusión"],
    selectionsort: ["Ordenamiento de selección"],
    quicksort: ["Ordenamiento rápido"],
    binarysearch: ["Búsqueda binaria"],
    linearsearch: ["Búsqueda lineal"],
    exponentialsearch: ["Búsqueda exponencial"],
    caesarcipher: ["Cifrado Cesar"],
    bellmanford: ["Bellman Ford"],
    doublylinkedlist: ["Doble lista vinculada"],
    singlylinkedlist: ["Lista singular vinculada"],
    averagemean: ["Promedio"],
    fibonaccinumbers: ["Numeros_Fibonacci"],
    harrisdetector: ["Detector de Harris"],
    coinchange: ["Cambio de monedas"],
    longestcommonsubsequence: ["Subsecuencia común más larga"],
  },
  categories: {
    sorting: "Sorts",
    sorters: "Sorts",
    sort: "Sorts",
    searching: "Searches",
    search: "Searches",
    other: "Others",
    misc: "Others",
    maths: "Math",
    hash: "Hashing",
    hashes: "Hashing",
    graph: "Graphs",
    divideconquer: "Divide And Conquer",
    string: "Strings",
  },
};
